# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - haveged

- name: Start/enable required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: true
  with_items:
    - haveged

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ aptly_configuration_directory }}"

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: aptly/aptly.conf.j2
      dest: "{{ aptly_configuration_directory }}/aptly.conf"
    - src: aptly/nginx.conf.j2
      dest: "{{ aptly_configuration_directory }}/nginx.conf"

- name: Run service
  docker_service:
    project_name: aptly
    definition:
      version: '2'
      services:
        aptly:
          restart: unless-stopped
          image: "{{ aptly_image }}"
          environment:
            FULL_NAME: "{{ aptly_configuration['full_name'] }}"
            EMAIL_ADDRESS: "{{ aptly_configuration['email_address'] }}"
            GPG_PASSWORD: "{{ aptly_configuration['gpg_password'] }}"
          volumes:
            - "{{ aptly_configuration_directory }}/aptly.conf:/etc/aptly.conf:ro"
            - "database:/opt/aptly/db"
            - "storage:/opt/aptly"
        nginx:
          restart: unless-stopped
          image: "{{ nginx_image }}"
          volumes:
            - "{{ aptly_configuration_directory }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
            - "storage:/opt/aptly:ro"
          ports:
            - "{{ aptly_nginx_host }}:{{ aptly_nginx_port }}:80"
          environment:
            VIRTUAL_HOST: "{{ aptly_configuration['virtual_host']|default('aptly') }}"
          networks:
            mirror:
              aliases:
                - aptly
      volumes:
        database:
        storage:
      networks:
        mirror:
          external: true
