---
- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_mirror }}"

- name: Create overlay network
  docker_network:
    name: mirror

- name: aptly - include tasks
  include: aptly.yml
  tags: aptly
  when: configure_aptly|bool

- name: registry - include tasks
  include: registry.yml
  tags: registry
  when: configure_registry|bool

- name: nginx - include tasks
  include: nginx.yml
  tags: nginx
  when: configure_nginx|bool
