---
- name: registry - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ registry_configuration_directory }}"

- name: registry - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: registry/registry.yml.j2
      dest: "{{ registry_configuration_directory }}/config.yml"

- name: registry - run service
  docker_service:
    project_name: registry
    definition:
      version: '2'
      services:
        registry:
          restart: unless-stopped
          image: "{{ registry_image }}"
          environment:
            VIRTUAL_HOST: "{{ registry_configuration['virtual_host']|default('registry') }}"
          volumes:
            - "{{ registry_configuration_directory }}:/etc/docker/registry"
            - "storage:/var/lib/registry"
          ports:
            - "{{ registry_host }}:{{ registry_port }}:5000"
          networks:
            mirror:
              aliases:
                - registry
      volumes:
        storage:
      networks:
        mirror:
          external: true
