---
- name: Install python version 2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python version 2
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Playbook for prearations
  hosts: all

  vars:
    operator_user: ubuntu
    operator_group: ubuntu
    operator_user_id: 1000
    operator_group_id: 1000
    docker_user: ubuntu

  roles:
  - role: osism.operator
  - role: osism.docker

- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    operator_user: ubuntu
    operator_group: ubuntu

  roles:
  - role: ../../ansible-mirror
